Jangoes initial version build
jangoes/jangoes-ios pull request #1
Opened 2021-05-05 03:21 UTC by jangoes

2021-05-05 06:16 UTC, jaimejazarenoiii requested changes
I haven't finished checking, PR is too huge, please dissect it to multiple PRs. Use cherry pick, quite hard to review 😢

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Cart/CartViewController.swift
> +extension CartViewController: UICollectionViewDelegate, UICollectionViewDataSource,
separate this

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/AddedToCartView.swift
> +        let tap = UITapGestureRecognizer(target: self, action: #selector(handleTap))
In RxSwift this is doable, not sure in reactiveswift

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Model/Switcher.swift
> +    var reverse: Self {
toggle or reverse?

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Model/Switcher.swift
> +    var reverse: Self {
also this is mutation better use func for this

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/ShopViewController.swift
> +        viewModel.shop.signal.observeValues { [weak self] _ in
even if it's just one, you still need to move it to a separate func

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/ShopViewController.swift
> +        tableView.register(ShopProfileTableCell.self, forCellReuseIdentifier: "headerCell")
normally there's a helper in stack over flow for avoiding manual string for the cell reuse identifier

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/ShopViewController.swift
> +            let mapSize = width / 2
a lot of magic numbers here, create a const variable for it

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/ShopViewController.swift
> +        viewModel.createOrder(for: product) { isAddedToCart in
weak self?

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/ShopViewController.swift
> +        viewModel.deleteOrder(for: product)
will this delete all product in cart?

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Table Cell/Collection Cell/ProductCollectionCell.swift
> +    func createOrder(for product: Product) {}
is the `{}` necessary here/

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Table Cell/Collection Cell/ProductCollectionCell.swift
> +protocol ProductCellDelegate: AnyObject {
```suggestion
protocol ProductCellDelegate: class {
```

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Table Cell/Collection Cell/ProductCollectionCell.swift
> +        didSet {
instead of didSet why not use the reactive bindings fully?

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Table Cell/Collection Cell/ProductCollectionCell.swift
> +        didSet {
This will confuse devs if you're mixing this kind of implementation with reactive

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Table Cell/Collection Cell/ProductCollectionCell.swift
> +        didSet {
instead of didSet maybe make this variables private, then expose a function for mutating variables here?

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Table Cell/Collection Cell/ProductCollectionCell.swift
> +        containerView.snp.makeConstraints { (make) in
same sentiments from previous comments, separate

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Table Cell/ProductListTableCell.swift
> +extension ProductListTableCell: UICollectionViewDelegate, UICollectionViewDataSource,
1 extension 1 file as much as possible

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Table Cell/ShopProfileTableCell.swift
> +    private var sideOffset: CGFloat = 30
side? which side? is it all corners? then maybe cornersOffset? or is it just horizontalOffset? verticalOffset?

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Table Cell/ShopProfileTableCell.swift
> +                            addressString = addressString + subLocality + ", "
create a helper for this? It's being use repetitively

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Custom Views/View Add-ons/Utility/Utility.swift
> +    static func decodedImage(data: String) -> UIImage {
why is the data in string? Shouldn't this be Data type

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Home/HomeTableCell/ShopTableViewCell.swift
> +        didSet {
Same sentiments

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/Profile/ProfileViewController.swift
> +
extra lines

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/TabBar/TabNavigationItem.swift
> +        for i in 0 ..< menuItems.count {
forEach?

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/TabBar/TabNavigationItem.swift
> +        for i in 0 ..< menuItems.count {
separate this, init is too huge

2021-05-05 06:16 UTC, jaimejazarenoiii commented on Jangoes/View/TabBar/TabNavigationItem.swift
> +        self.setNeedsLayout()
unnecessary self

2021-05-06 03:18 UTC, jangoes commented on Jangoes/View/Authentication/Sign in/SignInSetup.swift
> +        view.addSubview(headerView)
Adjusted sign in view, will adjust other views as well

2021-05-06 10:17 UTC, jangoes commented on Jangoes/View/Common/Shop View/Table Cell/Collection Cell/ProductCollectionCell.swift
> +    func createOrder(for product: Product) {}
Yes, for optional delegates

2021-05-06 10:19 UTC, jangoes commented on Jangoes/View/Common/Shop View/Table Cell/Collection Cell/ProductCollectionCell.swift
> +protocol ProductCellDelegate: AnyObject {
Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead

occurs in latest swift version, but I have adjusted it according to your preference

2021-05-07 00:48 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Table Cell/Collection Cell/ProductCollectionCell.swift
> +protocol ProductCellDelegate: AnyObject {
Ohhh TIL 👏🏻

2021-05-07 00:49 UTC, jaimejazarenoiii commented on Jangoes/View/Common/Shop View/Table Cell/Collection Cell/ProductCollectionCell.swift
> +    func createOrder(for product: Product) {}
So meaning you need to call the parent func still not leave this one blank

2021-05-07 00:50 UTC, jaimejazarenoiii commented on Jangoes/View/Authentication/Sign in/SignInSetup.swift
> +        view.addSubview(headerView)
What'd u mean?

2021-05-07 08:30 UTC, jangoes commented on Jangoes/View/Common/Shop View/ShopViewController.swift
> +        viewModel.deleteOrder(for: product)
No, this will only delete 1 product in the cart

2021-05-07 14:28 UTC, jangoes commented on Jangoes/View/Authentication/Sign in/SignInSetup.swift
> +        view.addSubview(headerView)
I mean, I have implemented it already in the SignInViewController and I will also implement this coding structure in the other view controllers as well. 😅😅😅

2021-05-10 03:06 UTC, jangoes commented on Jangoes/View/Authentication/Sign in/SignInViewController.swift
> +    weak var coordinator: AuthenticationCoordinator?
This is actually not a delegate, I am following this one: https://www.hackingwithswift.com/articles/71/how-to-use-the-coordinator-pattern-in-ios-apps

2021-06-15 07:40 UTC, merged